### ISSUE TITLE
Alle bestaande goals canvassen voorzien van links bij de user-stories

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#13]
- [x] BAG bevragen
- [x] BRK bevragen
- [ ] BRK historie
- [x] BRK event sourcing
- [x] BRP bevragen
- [ ] BRP historie
- [x] BRP reisdocumenten
- [X] BRP bewoning
- [ ] BRP tabellen
- [ ] BRP update API
- [x] HR bevragen
- [x] WOZ bevragen
- [ ] BGT bevragen
- [ ] Web-Security

**Comment by JohanBoer** [comment]
Volgens mij heeft @CathyDingemanse inmiddels alle Goals-canvassen voorzien van links.

**Comment by CathyDingemanse** [comment]
> Volgens mij heeft @CathyDingemanse inmiddels alle Goals-canvassen voorzien van links.

Ja, maar bij bewoning krijg ik een foutmelding als ik de link aanklik.

**Comment by CathyDingemanse** [comment]
@JohanBoer ik jheb ook een goals canvas voor reisdocs gemaakt inclusief links. Zou jij die naar main kunnen meenemen?

**Comment by JohanBoer** [comment]
Voor bewoning past Cathy de nummers (ex- BRP-bevragen nummers) in de links nog aan naar de issuenummers van BRP-bewoning.

**Comment by fsamwel** [comment]
BRP historie moet nog worden gemaakt

**Comment by melsk-r** [comment]
BRP Bewoning en BRP Reisdocumenten zijn gecorrigeerd. Ik assign dit issue weer aan Cathy voor het aanmaken van de nog ontbrekende Goals Canvases (bijv. op BRP historie).

**Comment by fsamwel** [comment]
BRP tabellen en BRP update en web Security wordt geen goals canvas gemaakt.

BGT heeft geen prioriteit

BRP historie en BRK historie gaat Cathy maken. Hier nieuw issue voor maken
