### ISSUE TITLE
Alle repos voorzien van standaard versielabels conform v1.2

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal#14]

**Comment by melsk-r** [comment]
Dit is gedaan voor de hele BRK en BRP.
De action die Melvin heeft gemaakt doorzetten naar de andere repo's.
Cathy kijkt dan of er  op die andere repo's nog labels aangemaakt moeten worden.

**Comment by melsk-r** [comment]
Cathy heeft de andere repo's ook gecheckt op het bestaan van deze labels.

Het gaat hier om de action 'generate-user-stories-md.yml' (zie Haal-Centraal-BRK-bevragen/.github/workflows/).

Volgens Cathy werkt deze nog niet goed. Melvin gaat er naar kijken.

**Comment by MelvLee** [comment]
Voor brk bevragen is de overzicht van user stories op te vragen met de volgende urls:

- https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/user-stories-prod
- https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/user-stories-dev

De user stories zijn aflopend gesorteerd op issue id.

**Comment by melsk-r** [comment]
Deze links zijn nu ook geactiveerd in de BRK Bevragen GitHub Pages omgeving.

**Comment by melsk-r** [comment]
Door Melvin vervaardigde action (workflow) is uitgerold op de repo's 'BAG Bevragen', 'BRK Bevragen', 'BRK Historie', 'BRP Bevragen', 'BRP Historie', 'BRP Bewoning', 'BRP Reisdocumenten', 'BRP Tabellen' en 'BRP Update API'.

**Comment by CathyDingemanse** [comment]
Gaat niet goed:
de repo's BRP bevragen, BRP historie en HR bevragen geven geen user stories. Voor BRP bevragen zijn de user stories met label v1.1. gesloten.

**Comment by melsk-r** [comment]
BRP Historie toont bij mij wel de userstories op de juiste wijze. Het kan zijn dat je de pagina na laden moet verversen met Ctrl+F5.

Met HR bevragen hebben we nog een probleempje met de workflow. Daar ben ik nog mee bezig.

BRP Bevragen heb ik inmiddels hersteld en zou nu wel een overzicht van de user stories moeten geven.

**Comment by melsk-r** [comment]
Ook bij HR bevragen worden de userstories nu op de gewenste wijze getoond.
Ik denk dat dit issue afgesloten kan worden.
