### ISSUE TITLE
filtering user stories op productie- en io versie 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal#15]
Ha Melvin, zou jij de lijstjes met user stories kunnen filteren? 
Alles wat in productie is (laatste productieversie + labels voorgaande versies). 
De user stories die horen bij de versie in ontwikkeling moeten worden gefilterd op dat versielabel.

Zodra IO in productie gaat worden de user user stories van deze versie aan de user stories productieversie toegevoegd.

**Comment by MelvLee** [comment]
Middels een GitHub Action wordt een pagina gegenereerd voor alle issues met labels 'User Story', 'BRK bevragen v1.2.1', 'BRK bevragen v1.2', 'BRK bevragen v1.1' en 'BRK bevragen v1.0'. Het zijn er nu in totaal 9 issues die hieraan voldoen.

@CathyDingemanse Zie: https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/user-stories-prod

**Comment by CathyDingemanse** [comment]
Ik heb alle labels omgelabeld en alle stories van een versienummer voorzien.

**Comment by melsk-r** [comment]
Ziet er inderdaad goed uit. Ik zou wel in de titels van deze pagina's ook het versie nummer meenemen.
De gegenereerde pagina's kunnen nu aan de side navigatie gekoppeld worden.

Action "_publish 'in productie' en 'in ontwikkeling' user stories_" kan volgens mij ook op de andere repositories beschikbaar gesteld worden (waar van toepassing met andere parameters) waarna we ook daar de resultaten aan de side navigatie kunnen koppelen.

**Comment by melsk-r** [comment]
Deze kan uitgerold worden op de andere repo's.

**Comment by JohanBoer** [comment]
Workflow moet nog uitgerold worden op de repositories. 
Daarvoor moet nog een secret worden aangemaakt en toegevoegd worden aan de repositories.

**Comment by melsk-r** [comment]
Er is inmiddels een secret op organisatie niveau aangemaakt. Deze is ook getest en bruikbaar bevonden. 

Het access token dat gebruikt wordt door de secret is gekoppeld aan mijn user account. Dat lijkt me echter geen goede constructie aangezien de mogelijkheid bestaat dat ik ooit geen beheerder meer ben van de GitHub organisatie VNG-Realisatie. Het is daarom beter om een persoon onafhankelijk account te creëren, daarop een acces token te genereren en die aan de secret te koppelen. Ik ga dit bespreken. In de tussentijd hoeft dit een uitrol niet in de weg te staan.

De ‘generate-user-stories-md.yml’ script kan nu dus worden uitgerold naar de andere HC repo's. Per repo moet er wel wat worden aangepast, nl wat in productie staat en wat in ontwikkeling.

**Comment by melsk-r** [comment]
Achteraf was een secret op organisatie niveau niet nodig. De GitHub variabele GITHUB_TOKEN wordt nu gebruikt waarvoor verder niets gedaan hoeft te worden.

In GitHub Pages zijn de correcte issuelijsten nu geimplementeerd behalve op die van 'BRK Event sourcing', 'HR Bevragen', 'WOZ Bevragen', 'BGT Bevragen' en 'HC Web Security'.

**Comment by melsk-r** [comment]
Op alle hierboven gemelde repo's kunnen alle userstories getoond worden.
Cathy introduceert daar waar nodig nog het label 'User Story' en koppelt deze aan de van toepassing zijnde issues.

**Comment by melsk-r** [comment]
Inmiddels worden op alle GitHub Pages pagina's de userstories op de juiste wijze getoond.
Wat mij betreft kan dit issue gesloten worden.

**Comment by fsamwel** [comment]
dit is gedaan. alleen moet target: blank uit config yaml

**Comment by melsk-r** [comment]
Ook die laatste aanpassing is uitgevoerd.
