### ISSUE TITLE
readme aanpassen van alle repo's

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal#18]
Moet identiek zijn aan de index

- [x] BAG bevragen
- [x] BRK bevragen
- [ ] BRK historie
- [x] BRK event sourcing
- [x] BRP bevragen
- [x] BRP historie
- [x] BRP Reisdocumenten
- [x] BRP Bewoning 
- [x] BRP tabellen
- [x] BRP update
- [x] HR bevragen
- [x] WOZ bevragen
- [x] BGT bevragen

**Comment by fsamwel** [comment]
BRK historie heeft nog helemaal geen vulling op zowel docs/index als op readme
