### ISSUE TITLE
"dubbele repo's" uit de menu's

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal#19]
zoals kadasterpersonen, totdat een opsplitsing beslissing is genomen en doorgevoerd.

**Comment by melsk-r** [comment]
Kadasterpersonen is nu uit de top navigation verwijderd.

@CathyDingemanse Je zegt 'zoals' welke repo's wil je nog meer verwijderd hebben?

**Comment by melsk-r** [comment]
Alle dubbele repo's zijn verwijderd. Dit issue mag gesloten worden.
