### ISSUE TITLE
Creëren script voor uitvoeren commit op alle repo's

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal#23]
Om wijzigingen op het theme zichtbaar te maken in de van dat theme gebruikmakende repo's moeten die eerst opnieuw gebuild worden. Dat kan door daar eerst een commit op uit te voeren. Er zijn nu 15 repo's die we op GitHub Pages publiceren dus dat is best een karweitje dat verder niets oplevert. 

Misschien kan dit ook met een script geregeld worden. N.m.m. moet dat script dan het build proces op alle repo's opstarten.

**Comment by MelvLee** [comment]
Ik heb een GitHub Action 'gh-pages-rebuild.yml' toegevoegd waarmee dit kan worden gerealiseerd. Het wordt alleen niet gedaan bij een commit omdat ik dit tricky vind. Als er nl. een fout zit in de commit, dan kunnen in principe alle remote repo's hierdoor worden gebroken.
Er moet wel wat worden geconfigureerd om dit allemaal te laten werken. Ik heb geen rechten om dit zelf te doen:

- Er moet een access token worden gegenereerd: Zie [create a personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token). Vink de **repo** checkbox. Alle sub-checkboxen moeten ook zijn aangevinkt
- Deze token moet als secret met als naam USER_TOKEN worden toegevoegd aan de **jekyll-theme-haal-centraal** repo onder **Settings/Secrets**
- Op dit moment worden alleen de haal-centraal en haal-centraal-brp-bevragen repo getriggered. Als de Action werkt moeten voor alle Haal Centraal repo's met GitHub Pages aan een step worden toegevoegd in de Action

De Action is te vinden onder de [Actions](https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal/actions?query=workflow%3A%22Trigger+GitHub+Pages+rebuild+at+remote+repos%22) tab. Selecteer de Action en klik op de **Run workflow** button

**Comment by melsk-r** [comment]
Melvin,

* Ik verwachtte dat je de betreffende yaml aan de onderliggende repo had toegevoegd. Daar zie ik hem echter niet. Bij BRP bevragen zie ik hem echter ook niet.
* Ik neem aan dat ik de token niet voor elke repo apart hoef te genereren.

**Comment by MelvLee** [comment]
> 
> 
> Melvin,
> 
>     * Ik verwachtte dat je de betreffende yaml aan de onderliggende repo had toegevoegd. Daar zie ik hem echter niet. Bij BRP bevragen zie ik hem echter ook niet.
> 
>     * Ik neem aan dat ik de token niet voor elke repo apart hoef te genereren.
> 
> 
> Ik heb de token i.i.g. al gegenereerd dus ik kan e.e.a. testen als ik weet waar ik de action kan vinden.

De Action is toegevoegd aan de jekyll-theme-haal-centraal-repo. Hij is te vinden onder de [Actions](https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal/actions?query=workflow%3A%22Trigger+GitHub+Pages+rebuild+at+remote+repos%22) tab. De USER_TOKEN key moet in die repo worden toegevoegd.

**Comment by melsk-r** [comment]
@MelvLee Top. Volgens mij werkt het. Er wordt i.i.g. netjes een nieuwe deployment aangemaakt.
Wil jij nog checken of kan ik de andere repo's ook aan de yaml toevoegen?

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee Top. Volgens mij werkt het. Er wordt i.i.g. netjes een nieuwe deployment aangemaakt.
> Wil jij nog checken of kan ik de andere repo's ook aan de yaml toevoegen?

Het ziet er goed uit. Je kan de andere repo's aan de yaml toevoegen.

**Comment by melsk-r** [comment]
De andere repo's zijn ook aan de yaml toegevoegd en het is getest. Issue kan gesloten worden.
