### ISSUE TITLE
Vullen readme en index voor Haal-Centraal-Web-Security

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#25]
De repo Haal-Centraal-Web-Security is nog helemaal leeg, inclusief de readme en docs/index.
En er zijn nog geen user stories toegevoegd.

@CathyDingemanse Kunnen we dat nu vullen, of moet voorlopig de link uit het top-menu worden gehaald?

**Comment by melsk-r** [comment]
Melvin heeft een aantal leuke illustraties gemaakt die in de repo staan en kunnen aan de readme en de GitHub pages toegevoegd worden.
