### ISSUE TITLE
De planning pagina geeft een foutmelding

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal#27]
De[ pagina waarop de planning moet worden getoond](https://vng-realisatie.github.io/Haal-Centraal/planning) geeft een foutmelding.
De link naar 'https://eu-rm.roadmunk.com/publish/4ac89376551785bace5e22f09c8247f307e1c061' loopt blijkbaar dood.

**Comment by CathyDingemanse** [comment]
Is mij bekend, wordt aan gewerkt...!

**Comment by melsk-r** [comment]
Is aangepast.
