### ISSUE TITLE
Betekenis van de term 'live' in het neerklappende navigatie menu van 'Producten' is niet duidelijk

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal#28]
Het is niet duidelijk wat 'live' nu precies betekent. Ik denk dat wel duidelijk is dat het een status is maar wat houdt dat dan in.
Daarnaast wordt binnen de productpagina's bij de specificaties soms nog een andere status getoond ('IO') die n.m.m. in tegenspraak is met de status 'live' ([voorbeeld](https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/)).

**Comment by JohanBoer** [comment]
Ik denk dat we een duidelijk onderscheid moeten maken van een landelijk beschikbare API (BRK, BAG) waarvan je heel goed kan zeggen dat ze live zijn en de release van API-specificaties (zoals de BRP-bevragen) waarvan je hooguit kan stellen dat het de meest actuele versie van de specificaties is.

**Comment by melsk-r** [comment]
Helemaal mee eens. Die laatste status is dan van hetzelfde type als de statusaanduiding 'IO' in de side navigation.

**Comment by CathyDingemanse** [comment]
Met LIVE wordt bedoeld dat de API klaar voor gebruik wordt aangeboden door een landelijke provider. De BAG en de BRK in dit geval.
