### ISSUE TITLE
Wat wordt bedoelt met 'Wijzigingen of toevoegingen doen deelproducten via een pull request.'

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal#29]
Het is mij niet duidelijk wat wordt bedoelt met het 3e item van de genummerde lijst onder 'Bijdragen' in '[Hoe kun je bijdragen?](https://vng-realisatie.github.io/Haal-Centraal/hoe-kun-je-bijdragen)'.

Wellicht dit item iets anders formuleren.

**Comment by CathyDingemanse** [comment]
Done!

**Comment by melsk-r** [comment]
Duidelijk zo!
