### ISSUE TITLE
Afhandelen issue met lengte zoekparameter in BAG-bevragen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#33]
Discussie m.b.t. nieuwe majorversie n.a.v. beperken parameter-lengte afronden. Frank stelt oplossing voor aan Mark (geen foutmelding bij >255 maar gewoon een leeg resultaat teruggeven. ) Issue #364 gaat hierover --> naar de backlog met label “volgende major” en "breaking".

**Comment by JohanBoer** [comment]
Frank heeft ons voorstel gecommuniceerd naar Mark, maar heeft nog geen reactie ontvangen.

**Comment by fsamwel** [comment]
Mark heeft geantwoord. Pull request(s) zijn gemerged naar develop en master
