### ISSUE TITLE
Versie 1.2.0 maken voor BRP-bevragen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#34]
BRP-Bevragen -- > Pull request #760 mergen ? Cathy heeft nog niet approved. -- Indien OK --- Release 1.2.0 maken. 
 Mergen en release aanmaken. Johan (check ook versienr in de OAS.)

**Comment by JohanBoer** [comment]
Bij het mergen van develop naar de master zijn er issues ontstaan in de JAV-sdk files die opgelost moeten worden. Melvin heeft een voorstel gedaan om dat af te handelen ( Zie mail dd 11-1-2021)

**Comment by JohanBoer** [comment]
Lokaal de master naar develop gemerged en die wijzigingen gemerged met de "develop" op de VNGR repo. 
Weet relatief zeker dat de PR nu goed gaat maar heb voor de zekerheid Frank en Melvin om een review gevraagd (korte check). 
Als de PR gemerged is kan v1.2.0 gemaakt worden

**Comment by JohanBoer** [comment]
Er blijken veel merge-issues te zijn. Met Frank doorgesproken. We kunnen onze vinger er niet opkrijgen waarom wijzigingen in de master nit in de develop terecht gekomen zijn bij de "merge master" in de oplossing die Melvin heeft aangedragen. 
Inhoudelijk is de wijziging naar v1.2.0 relatief beperkt. Ik ga nu een develop2 maken op basis van de huidige master en daarin de wijzigingen doorvoeren. 
Dan kunnen we ook redelijk "clean" reviewen.

**Comment by JohanBoer** [comment]
Release 1.2.0 aangemaakt.

**Comment by melsk-r** [comment]
Release 1.2.0 is nu ook aan de GitHub Pages pagina toegevoegd ter vervanging van 1.1.
Daarnaast is ook alvast versie 1.3.0 (IO) toegevoegd.
