### ISSUE TITLE
Reisdocumenten v0.9.0 en v1.0.0 maken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#35]
BRP-Reisdocumenten-Bevragen --> Pull request #6 mergen ? --> Melvin, Kay en Frank nog niet approved. Cathy ook reviewen ? Indien gemerged --> Versie 1.0.0 maken. Johan doet check op wijzigingen en stelt releasenotes op. Van huidige stand master een 0.9 aanmaken. Bij breacking change of twijfel terugkoppelen en nog geen 1.0.0 aanmaken

**Comment by JohanBoer** [comment]
Release v0.9.0 aangemaakt. Check op breaking changes nog doorvoeren inclusief check op linter warnings.

**Comment by JohanBoer** [comment]
Releasenotes gemaakt en yaml gechecked. 

Ik heb een [Pull Request](https://github.com/VNG-Realisatie/Haal-Centraal-Reisdocumenten-bevragen/pull/24) aangemaakt met de  een paar kleine wijzigingen. Daarbij heb ik Robert, Melvin en Frank uitgenodigd als reviewers. 

Zoals afgesproken bij deze de terugkoppeling bij Breaking changes. Zie pull request voor verdere uitleg. 
Als het Pull request ok is en de breaking changes acceptabel dan maak ik versie 1.0.0 aan.

**Comment by JohanBoer** [comment]
Frank overlegt met Kayo . 
Melvin kijkt er inhoudelijk nog even naar. 
Wordt nog teruggekoppeld of en hoe v1.0.0 straks wordt aangemaakt.

**Comment by melsk-r** [comment]
Repo's bevatten mogelijke breaking changes. 
Frank heeft met Kayo gesproken en ze hebben geen last van de operation ID's.
Johan heeft ook nog een maxlength aangepast, we verwachten echter niet dat dat een issue gaat zijn.

Johan gaat 1.0.0 aanmaken en publiceren.

**Comment by JohanBoer** [comment]
Ik heb inmiddels de versie 1.0.0 release aangemaakt. 

@melsk-r kan jij even checken waar de in_onderzoek.feature niet getoond wordt op de github-pages ?

**Comment by JohanBoer** [comment]
@melsk-r : Ook de Goals-canvas wordt nog niet getoond in het linker navigatie menu..... Moet ik daarvoor iets aanpassen ?

**Comment by melsk-r** [comment]
Goals Canvas wordt inmiddels wel getoond.
