### ISSUE TITLE
BRP-bewoning v0.9.0 maken en v1.0.0 issues verwerken 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#36]
BRP-Bewoning --> Eerst een 0.9 van de huidige versie maken -- check #760. 
 Noot: Alle verwijzing naar BRP -- laten verwijzen naar 0.9 versie van BRP in huidige master van Bewoning. Dan checken op resolven. Dan 0.9 bewoning aanmaken. Daarna alle issues verwerken die v1.0.0 gelabeled zijn. Na verwerking alle issues --> final check en dan release v1.0.0 aanmaken.

**Comment by JohanBoer** [comment]
Versie 0.9.0 is aangemaakt.

**Comment by melsk-r** [comment]
Johan heeft een PR opgevoerd. Deze moet nog gereviewed worden door Cathy en Frank.
Gemiddelde bewoningsduur gaan we niet opnemen. Over blijft dan gemiddeld aantal bewoners en inschrijven en uitschrijven. 
Melvin gaat in het feature beschrijven dat als de datum niet of gedeeltelijk onbekend is het gemiddeld aantal bewoners niet te berekenen is. Hetzelfde geldt voor het aantal uitverhuizingen.

**Comment by JohanBoer** [comment]
PR is gereviewed en Develop is gemerged met de master. 
Ook de wijzigingen in de features m.b.t. de onbekende datums is door Melvin doorgevoerd en staat in de master.
Inmiddels alle actions gedraaid en de labels staan allemaal netjes op groen

Ik wacht nog even tot we dit maandag allemaal bewust gezegend hebben alvorens v1.0.0 aan te maken.

**Comment by JohanBoer** [comment]
Ik zie net dat de releasenotes ontbreken. Die ga ik nog toevoegen.

**Comment by JohanBoer** [comment]
> Ik zie net dat de releasenotes ontbreken. Die ga ik nog toevoegen.

Done, release v1.0.0 aangemaakt
