### ISSUE TITLE
BRP-Historie-bevragen v0.9.0 maken en v1.0.0 aanmaken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#37]
BRP-Historie-Bevragen --> Eerst een o.9 release aanmaken met hudige stand van de master. Check hier ook eerst op verwijzingen naar de master van de BRP-bevragen repo en pas daar eerst deze verwijzing aan voordat er een 0.9 wordt aangemaakt. Dan releasenotes nog aanscherpen n.a.v. opmerkingen in Pull Request. Indien afgerond --> release v1.0.0 aanmaken. --> check ook adellijke titel impact van BRP_bevragen 1.3.0.

**Comment by JohanBoer** [comment]
Release v1.0.0 kan pas gemaakt worden als v1.2.0 release van BRP-bevragen er is. Er wordt een component (Partner) uit de BRP_Bevragen yaml gebruikt. Ook de definitie van Burgerservicenummer wordt hergebruikt.

Vraag is of er een 0.9.0 versie gemaakt moet worden. Wat nu in de master staat is al een forse aanpassing van de versie die het was toen deze endpoints nog in BRP-bevragen zaten. Verwijzingen naar common zijn al netjes 1.2.0. 
Er zijn dan tussen de 0.9.0 en de 1.0.0 maar kleine verschillen. Ik denk dat we beter direct de 1.0.0 kunnen aanmaken. 

Overigens ook in deze repo loopt de develop uit de pas met de huidige master. Ik vrees wederom merge-issues. Ik zou hier graag als we versie 1.0.0 gemaakt hebben ook de develop branch willen deleten en opnieuw op basis van de master willen aanmaken.

**Comment by JohanBoer** [comment]
Tip van Frank, Verwijs naar de 0.9 van BRP bevragen en de 1.0 van common --> maak daar een versie 0.9.0 van aan 
Daarna pas door met het aanmaken van een versie 1.0.0

**Comment by JohanBoer** [comment]
Frank achterhaald welke opdrachten naar Kayo gegaan zijn om de implementatie van BRP-Historie aan te passen aan wijzigingen die in BRP-bevragen zijn doorgevoerd zijn. Als we dat weten kunnen we versie 0.9.0 "reproduceren". 

Daarna maken we pas alles weer in orde voor release 1.0.0 .

**Comment by fsamwel** [comment]
Doorgevoerd in Den Haag zijn de volgende wijzigingen (met impact voor historie):

Locatie | parameter of property | wijziging | opmerking
-- | -- | -- | --
Verblijfplaats | identificatiecodeVerblijfplaats --> identificatiecodeAdresseerbaarObject | gewijzigd |  
VerblijfplaatsInOnderzoek | identificatiecodeVerblijfplaats --> identificatiecodeAdresseerbaarObject | gewijzigd |  
OntbindingHuwelijkPartnerschap | indicatieHuwelijkPartnerschapBeeindigd | toegevoegd |  
Verblijfstitelhistorie | indicatieVerblijfstitelBeeindigd | verwijderd |  
Verblijfstitel | datumOpneming | verwijderd |  
VerblijfstitelInOnderzoek | datumOpneming | verwijderd |  

Volgens specs in deze versie: https://app.swaggerhub.com/apis/DH-Sandbox/bevragingen-ingeschreven_personen/1.1.20200316#free

Hierna is ook de wijziging voor gelijktrekken verblijfplaats met BAG-adres doorgevoerd.
Ook het wijzigen van parameters naar camelCase is doorgevoerd (op datumVan en datumTotEnMet)

Nieuw/nog niet doorgevoerd is toevoegen OntbindingHuwelijkInOnderzoek.reden ([commit](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/commit/9d255fbaa908851d91d716037d97ffbbd3e0e157#)). Dit heb ik gemeld aan Kayo.

Ook nieuw/nog niet doorgevoerd is verplaatsen van adresregels voor buitenlands adres en ook voor NL adres vullen van adresregels (in de verblijfplaatshistorie) ([commit](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/commit/2128992937ce20a36711b369f16826d7529420c0#)).

**Comment by melsk-r** [comment]
Melvin gaat de versie van BRP Bevragen van November 2019 opleveren (openapi.yaml) aan Johan.
Johan gaat een 1.0.0 versie opleveren en beide versies diffen.
Dat moet dan de 0.9 versie BRP Historie bevragen van November 2019 opleveren.

**Comment by JohanBoer** [comment]
Ik heb in BRP-historie de openstaande PR (#28) gesloten en een nieuwe PR aangeboden. Dat zou versie 1.0.0 moeten worden. 
Ook releasenotes opgenomen met daarin de wijzigingen zoals Frank die geïnventariseerd heeft en de wijzigingen die in de vorige PR stonden en de wijzigingen die ik n.a.v. een verschillenanalyse met de door melvin aangeleverde openapi.yaml herb kunnen vinden.

**Comment by JohanBoer** [comment]
Openstaande punten van https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/pull/45 doornemen.

**Comment by JohanBoer** [comment]
> Openstaande punten van [VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen#45](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/pull/45) doornemen.

Zijn doorgenomen en voorstellen van Melvin en Frank voor de releasenotes  zijn overgenomen. 
Er staat nu een PR klaar om van develop naar de master over te zetten (https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/pull/46) 
Al die wijzigingen zijn inhoudelijk al beoordeeld. Deze PR geeft nog even de gelegenheid om door die wijzigingen te browsen als daar behoefte aan is. Ik check dat maandag ook even en dan kan release v1.0.0 aangemaakt worden

**Comment by fsamwel** [comment]
Robert gaat dit met Johan doen

**Comment by JohanBoer** [comment]
Zojuist release v1.0.0 aangemaakt
