### ISSUE TITLE
BRP-Update-API v1.0.0 maken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#38]
BRP-Update-API --> Robert maakt versie v1.0.0. Johan stuurt mail aan Lia voor testondersteuning door ProcessFive.

**Comment by JohanBoer** [comment]
Joeri Bekker van Maykin media heeft een voorstel gedaan om Open Personen als test-implementatie te gebruiken. Cathy heeft een voorstel gedaan om dat te verbinden met een referentie-implementatie van BRP-Update-Api. Dat is door Johan ook aan Lia voorsteld via mail.

**Comment by JohanBoer** [comment]
Tijdens werkbespreking kwam het idee naar voren om naast de update van persoonsgegevens ook ntificatie m.b.t. wijzigingen in de bewoning te sturen. 
Naast de persoon die kan worden ge-update worden --> ook voor de bewoning. 
Dus als je een persoon volgt wil je ook weten of er iets in de bewoning veranderd waar die persoon onderdeel van maakt.
Dit moeten we een keer in een ontwerp-sessie uitdiepen.

**Comment by melsk-r** [comment]
> Tijdens werkbespreking kwam het idee naar voren om naast de update van persoonsgegevens ook notificatie m.b.t. wijzigingen in de bewoning te sturen.
> Naast de persoon die kan worden ge-update worden --> ook voor de bewoning.
> Dus als je een persoon volgt wil je ook weten of er iets in de bewoning veranderd waar die persoon onderdeel van maakt.
> Dit moeten we een keer in een ontwerp-sessie uitdiepen.

Lijkt mij beter bovenstaande in een apart issue te plaatsen zodat ik dit issue kan sluiten zodra versie 1.0.0 is aangemaakt. Tenzij we bovenstaande functionaliteit nog in versie 1.0.0 opgenomen willen hebben natuurlijk.

**Comment by melsk-r** [comment]
Release 1.0.0 is aangemaakt.
