### ISSUE TITLE
BRP-Bevragen : Gestripte versie voor implementatie door RvIG maken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#42]
BRP-Bevragen --> Gestripte versie voor RvIG waar alle wettelijke belemmeringen worden uitgehaald (bv. aanschrijfwijze ) . Cathy zoekt op welke afspraken daarover gemaakt zijn en zet dat in een issue. Discussie over hoe we dit gaan doen in termen van branch, fork en/of release voeren we volgende week als Melvin er weer bij is.

**Comment by CathyDingemanse** [comment]
is al gedaan: 
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/765 
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/766

**Comment by fsamwel** [comment]
@MelvLee @CathyDingemanse  hebben we hier gisteren iets over besloten? Moet dit op een fork (aparte repo) of kan dit in een branch?

**Comment by MelvLee** [comment]
We hebben hier gisteren niet over gesproken. Ik denk dat een fork beter is. Ik denk dat het moeilijk is om uit te leggen dat je in een aparte branch moet gaan zoeken naar de gestripte versie. En wat als je straks meerdere versies wilt hebben. De versie in productie en een volgende versie? Ik denk dat dit niet is uit te sluiten en dan wordt het moeilijk om dat met branches van branches te beheren

**Comment by fsamwel** [comment]
Afgeleide gegevens in de IngeschrevenPersoon (die mogelijk verwijderd moeten worden):
- leeftijd
- naam. voorletters
- naam. aanhef
- naam. aanschrijfwijze
- naam. regelVoorafgaandAanAanschrijfwijze
- naam. gebruikInLopendeTekst
- verblijfplaats. adresregel1 (description en example wijzigen zodat alleen gevuld met verblijf buitenland en adres.feature vervalt)
- verblijfplaats. adresregel2 (description en example wijzigen zodat alleen gevuld met verblijf buitenland en adres.feature vervalt)

Ik twijfel of voorletters ook verwijderd moet worden. Deze is erg eenvoudig afgeleid van één gegeven. Kan je dus ook zien als andere representatievorm en niet als verrijking. Zelfde geldt misschien ook voor leeftijd?

Meerdere andere velden zijn ook "afgeleid" van een gegeven, maar die zie ik als alleen gewijzigde representatievorm. Bijvoorbeeld indicatieOverleden (06.08.10 is niet leeg) of vanuitVertrokkenOnbekendWaarheen (08.14.10==0000). Deze mogen denk ik wel in de API blijven.

@CathyDingemanse welke gegevens moeten worden verwijderd uit de het antwoord?

**Comment by fsamwel** [comment]
@melsk-r @JohanBoer kunnen jullie een fork maken voor de "gestripte" BRP bevragen op VNG-Realisatie. Ik lijk daar geen rechten op te hebben.
Mocht je de fork een andere naam moeten geven, dan heet het "Haal-Centraal BRP Bevragen RvIG" (net afgestemd met @CathyDingemanse)

**Comment by melsk-r** [comment]
@fsamwel @MelvLee Ik vraag me af of forking de juiste techniek is. Als ik fork dan maak ik immers een copy van de upstream repository in mijn eigen account. Dat kan niet de bedoeling zijn. Ten eerste omdat het bestaan van de repository daarmee afhangt van het bestaan van mijn account en ten tweede omdat dit voor mij belemmerend werkt aangezien ik gebruik maak van deze fork als ik de repository lokaal wil clonen.

Er wordt in de documentatie van GitHub wel gesproken over de mogelijkheid om een mirror van een repo te maken. Daarvoor zou je na het clonen van de repo het volgende commando moeten uitvoeren:

`$ git push --mirror https://github.com/exampleuser/new-repository.git`

Dit heb ik gedaan maar ik vraag me af of dit is wat jullie willen. Er is nu immers geen enkele relatie tussen de oorspronkelijke repo en deze repo.

**Comment by melsk-r** [comment]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG

**Comment by fsamwel** [comment]
Robert heeft inmiddels repo hiervoor gemaakt. Ik heb deze "opgeruimd" zodat deze klaar is voor het feitelijk strippen en dit geen marge conflicten meer geeft.

**Comment by fsamwel** [comment]
@CathyDingemanse hoe zit het eigenlijk met historie? Zien ze dat ook als aanvullende logica die we toepassen (er is wat logica nodig om de juiste historie te tonen, zie historie features)? Gaan ze de historie wel helemaal als gedefinieerd bouwen, of toch niet?

**Comment by fsamwel** [comment]
te verwijderen velden: zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/765

**Comment by fsamwel** [comment]
@melsk-r ik denk dat er toch GitHub Pages nodig is voor de RvIG versie, onder andere om de Swagger en Redoc specificaties en de releasenotes goed te kunnen tonen. Kan jij dit instellen op de repo?

**Comment by fsamwel** [comment]
Met strippen van de specificaties wacht ik op de v1.2.0, zodat ze in de basis zeker gelijk zijn

**Comment by melsk-r** [comment]
> 
> 
> @melsk-r ik denk dat er toch GitHub Pages nodig is voor de RvIG versie, onder andere om de Swagger en Redoc specificaties en de releasenotes goed te kunnen tonen. Kan jij dit instellen op de repo?

Ja, geen probleem. Alleen kom ik dan toch weer terug op de vraag die ik gisteren stelde. 
Hoe gaan we deze gestripte versie publiceren? Welk versienummer gaat dit krijgen?

**Comment by fsamwel** [comment]
is het versienummer nu van belang voor het activeren van GitHub Pages op de repo?

Ik ben nu uitgegaan (o.a. in releasenotes en readme) van het gelijk houden van de versienummers tussen BRP-bevragen en BRP-bevragen-RvIG. Dat wordt dus straks v1.2.0.

**Comment by melsk-r** [comment]
> is het versienummer nu van belang voor het activeren van GitHub Pages op de repo?

Jullie vragen, ik draai maar ik moet wel weten wat ik moet draaien. Als ik geen versienummer moet gebruiken dan vind ik het prima als ik dat maar weet. Bij HR Bevragen is dat immers ook niet gedaan.
Onder welke naam wil je het opnemen in de top navigatie van https://vng-realisatie.github.io/Haal-Centraal/ ?

Tonen we nu trouwens al ergens de releasenotes?

**Comment by JohanBoer** [comment]
Eergisteren (of gisteren ???) hebben we gesproken dat we alles klaar gaan zetten en beschikbaar gaan stellen voor het RvIG om te bouwen. Hoe we dit gaan publiceren zou pas een kwestie worden als het RvIG klaar is en er eventueel gemeenten (leveranciers) gaan aanhaken. Laten  we voorlopig deze gestripte versie even buiten de https://vng-realisatie.github.io/Haal-Centraal/ ? houden. 

Ik denk dat het veel meer vragen dan duidelijkheid oplevert als wij twee varianten (let wel, geen versies) van de BRP-bevragen API gaan publiceren op dit moment.

**Comment by melsk-r** [comment]
> 
> 
> @melsk-r ik denk dat er toch GitHub Pages nodig is voor de RvIG versie, onder andere om de Swagger en Redoc specificaties en de releasenotes goed te kunnen tonen.

Dit kan ook nog steeds in de readme opgenomen worden.

**Comment by fsamwel** [comment]
Toch hebben we denk ik GitHub Pages nodig, bijvoorbeeld/met name voor het tonen van de specificaties in Redoc en Swagger-UI. Ook andere documenten, zoals getting started en release notes zijn nu geoptimaliseerd voor GitHub Pages, niet voor tonen op GitHub als Markdown. Dat hoeft niet te betekenen dat deze ook moet worden opgenomen in het menu van de website, wel dat pages geactiveerd moet zijn.

**Comment by fsamwel** [comment]
> Dit kan ook nog steeds in de readme opgenomen worden.

Hoe?

**Comment by melsk-r** [comment]
> 
> 
> > Dit kan ook nog steeds in de readme opgenomen worden.
> 
> Hoe?

Ik bedoel dat er in de Readme gewoon nog steeds links opgenomen kunnen worden waarmee de Swagger en Redoc pagina's worden geöpend zoals dat nu ook nog steeds in de readme voor https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen wordt gedaan.

En ja, natuurlijk kunnen we GitHub Pages activeren zonder deze in de HaalCentraal Website mee te nemen. De GitHub Pages van deze repository is dan niet via de top navigatie te benaderen maar via diens top navigatie zijn dan wel de GitHub Pages van de andere repositories te benaderen.

**Comment by fsamwel** [comment]
De link voor bijvoorbeeld Swagger-ui in de readme van BRK-bevragen verwijst naar https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/swagger-ui.

En die werkt bij BRK-bevragen alleen omdat daar github pages is geactiveerd. Op BRP-bevragen-RvIG werkt die link (die al in de readme zit) niet.

**Comment by melsk-r** [comment]
Maar we hadden er toch ook al een link inzitten voordat we GitHub Pages gingen gebruiken?
Kijk maar eens op https://github.com/VNG-Realisatie/Regels-bij-activiteiten. Op die repo is GitHub Pages niet geactiveerd maar werkt de link naar Swagger wel. Hoe dat zit met Redoc weet ik niet maar dat zal Melvin vast nog wel weten.

**Comment by MelvLee** [comment]
> 
> 
> Maar we hadden er toch ook al een link inzitten voordat we GitHub Pages gingen gebruiken?
> Kijk maar eens op https://github.com/VNG-Realisatie/Regels-bij-activiteiten. Op die repo is GitHub Pages niet geactiveerd maar werkt de link naar Swagger wel. Hoe dat zit met Redoc weet ik niet maar dat zal Melvin vast nog wel weten.

Op https://github.com/VNG-Realisatie/Regels-bij-activiteiten gebruiken ze de oude manier (petstore) om een openapi.yaml te tonen. Als we een OAS op de nieuwe manier willen tonen, dan moeten die pagina's worden gehost door een web server, wat GitHub ook is. Maar daarvoor hoeft je GitHub Pages niet aan te zetten op de RVIG repo. Je kan ook in de haal centraal repo een redoc/swagger-ui pagina aanmaken die de openapi.yaml verwijst. Ik heb dat gedaan en een redoc pagina aangemaakt. Die geeft nu een foutmelding omdat ik naar de niet-genereervariant verwijst. Zie: https://vng-realisatie.github.io/Haal-Centraal/redoc-rvig

**Comment by melsk-r** [comment]
Frank past de index.md en readme.md aan. Ook naar het menu kijkt hij nog.

**Comment by JohanBoer** [comment]
Readme.md, index.md en de releasenotes staan klaar in een pull request. 
Frank kijkt het menu ook nog na.

**Comment by fsamwel** [comment]
Ook side navigatie aangepast in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG/pull/5

**Comment by fsamwel** [comment]
pull requests https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG/pull/5 en https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG/pull/6 staan in review

**Comment by melsk-r** [comment]
Johan en Cathy checken PR #5 en #6.
Opmerking: controleer alle documentatie in samenhang (#5)

**Comment by CathyDingemanse** [comment]
ik sta niet als reviewer voor VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG#6

**Comment by fsamwel** [comment]
volgens mij hebben we vorige week afgesproken dat we de RvIG repo laten vervallen en dus RvIG gaat bouwen op basis van de normale BRP-bevragen specificaties. Daarin hebben we opmerkingen en een apart document gemaakt met een opsomming van afgeleide gegevens die ze niet zullen leveren.

Dit issue kan gesloten worden, toch?

**Comment by melsk-r** [comment]
Dat is volgens mij inderdaad hetgeen we besloten hebben dus ik denk dat je gelijk hebt.

**Comment by JohanBoer** [comment]
Eens
