### ISSUE TITLE
Uitleg / Borgen van alle actions die door Melvin opgezet zijn.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#44]
Ook goede documentatie voor beheer en onderhoud hiervan maken. --> Robert en Johan doen dit samen met hulp van Melvin.

Melvin heeft al uitleg opgeleverd, maar dat is (voor mij in ieder geval) nog niet voldoende om zelf het beheer te kunnen doen. 
Deze kennis en zelfstandigheid is nodig bij de (toekomstige?) beheerders van de repositories.

**Comment by MelvLee** [comment]
Waar willen we dit soort content beheren? Ik denk dat dit soort content (nog) niet op de Haal Centraal website terecht moet komen. Als we het in deze repo willen beheren, dan kunnen we voor dit soort documentatie de 'beheer en onderhoud docs'  folder aanmaken

**Comment by melsk-r** [comment]
Ik stel voor het gewoon in onze [Kennisbank](https://github.com/VNG-Realisatie/API-Kennisbank) op te slaan. Desnoods in een nieuwe folder.

**Comment by MelvLee** [comment]
Ik heb geen rechten om een branch aan te maken op Kennisbank repo

**Comment by JohanBoer** [comment]
Ik ben geen admin op deze repo. @melsk-r : wil jij Melvin hier de juiste permissies geven ? 
PS: misschien handig mij hier ook admin te maken ?

**Comment by melsk-r** [comment]
@Melvin, je kunt je gang gaan.
@Johan, jij bent nu ook admin.

**Comment by MelvLee** [comment]
Ik heb een eerste aanzet gemaakt voor het documenteren van de Haal Centraal GitHub Actions workflows: https://github.com/VNG-Realisatie/API-Kennisbank/blob/docs/haal-centraal-github-actions/GitHub%20Actions/haal-centraal.md
Jullie kunnen er al naar kijken en eventueel feedback geven.

**Comment by JohanBoer** [comment]
> Ik heb een eerste aanzet gemaakt voor het documenteren van de Haal Centraal GitHub Actions workflows: https://github.com/VNG-Realisatie/API-Kennisbank/blob/docs/haal-centraal-github-actions/GitHub%20Actions/haal-centraal.md
> Jullie kunnen er al naar kijken en eventueel feedback geven.

Ziet er goed uit. Er komen echter wel wat vragen bij mij op omdat ik geen recente develop ervaring heb. Ik zou bv. wat verdere uitleg van bash en van npm kunnen gebruiken (of een boek lezen... ?), maar ik ben zelf niet representatief. Als bash en npm voor Robert en Michiel wel gesneden koek zijn, dan hoeven we hier niet op aan te vullen. 

@michielverhoef zou jij hier ook eens mee willen kijken ? 

Overigens is zijn de "generate-postman..." en "user stories..." scripts nog niet beschreven, maar ik neem aan dat dat nog volgt...

**Comment by MelvLee** [comment]
Ja, de beschrijving voor generate-postman.. en user-stories... workflows komt nog. Ik zal ook wat uitleg van bash en npm toevoegen.

**Comment by MelvLee** [comment]
De documentatie voor de GitHub Action workflows en de in Haal Centraal gebruikte tooling is nu klaar. Ik heb het als pull request aangeboden

**Comment by melsk-r** [comment]
Ik ga de actions nog uitproberen op een andere GitHub repository. Wellicht komen daar nog zaken uit waarmee we de beschrijving kunnen aanscherpen.

**Comment by melsk-r** [comment]
Ik heb de actions 'lint-oas' en 'generate-sdks' nu werkende in een andere repository. Na een aanpassing in het script dat voor Melvin aanleiding is om het script nog robuuster te maken.
Verderop deze week gaan Melvin en ik kijken of we ook de action 'generate-postman-collection' werkende kunnen krijgen.

**Comment by melsk-r** [comment]
Ook de action 'generate-postman-collection' werkt nu.

Melvin gaat de beschrijving in https://github.com/VNG-Realisatie/API-Kennisbank/blob/docs/haal-centraal-github-actions/GitHub%20Actions nog aanvullen met informatie over het gebruik van het .spectral.yml bestand.

@MelvLee, had jij nog tijd besteed aan het robuuster maken de scripts?

**Comment by MelvLee** [comment]
@melsk-r, ik heb documentatie mbt spectral toegevoegd. Zie P.R. https://github.com/VNG-Realisatie/API-Kennisbank/pull/49

Verder ben ik nog aan het nadenken over het robuuster maken van de npm scripts

**Comment by melsk-r** [comment]
Documentatie lijkt me voor nu voldoende. Mocht e.e.a. later toch meer uitleg behoeven dan doen we dat dan. Voor nu sluiten we het issue.
