### ISSUE TITLE
instellen dat een closed issue automatisch op Done komt

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#46]

**Comment by melsk-r** [comment]
@fsamwel Ik heb het ingesteld. Ik ga het testen a.d.h.v. dit issue.

**Comment by melsk-r** [comment]
Werkt zoals gewenst. Wellicht ook uitrollen op andere repo's?

**Comment by fsamwel** [comment]
is dit niet al zo ingesteld op de andere repo's waar we een project gebruiken?

**Comment by melsk-r** [comment]
Ik heb het even gecheckt en bij enkele repo's was het niet zo ingesteld.
Daar heb ik het alsnog zo ingesteld.
