### ISSUE TITLE
Rol van "Open Personen" referentieimplementatie irt Update-API bespreken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#47]
Ik heb zojuist even rondgesnuffeld op de “Open Personen” website van maykin media, maar zijn zijn bij de implementatie van de BRP-API behoorlijk afgeweken van onze API_specificatie. 

Zie https://github.com/maykinmedia/open-personen/blob/master/src/openapi.yaml 
Het kan best zijn dat als je een consumer volgens onze API bouwt dat die dan niet breekt als je Open Personen bevraagt, maar zo diep ben ik er nog niet ingedoken. 

Als we echter op 1 of andere manier deze implementatie als referentie-implementatie in willen zetten zou die analyse wel gedaan moeten worden.

**Comment by melsk-r** [comment]
Robert stemt met Joeri af hoe dit zich verhoudt tot de BRP API.

**Comment by melsk-r** [comment]
OpenPersonen voldoet (nog) niet aan de BRP API specificaties dus komt het niet in aanmerking om als testsysteem te dienen.
Wij gaan kijken of we de BRP API repository in de componenten catalogus opgenomen kunnen krijgen.
