### ISSUE TITLE
Aanpassen casing path-parameters BRK-bevragen 1.3.0

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal#48]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/779

ZSM afronden

**Comment by JohanBoer** [comment]
Pull request staat klaar voor review

**Comment by CathyDingemanse** [comment]
> Pull request staat klaar voor review

Door wie? :-)
