### ISSUE TITLE
Toevoegen link naar stelselcatalogus onder "bronnen"

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal#53]
https://vng-realisatie.github.io/Haal-Centraal/ -> Onder het kopje “Producten” staan links naar API beschrijvingen van de BAG, BRK, BRP, HR, WOZ en BGT. Per beschrijving kan onder het kopje “Bronnen”  een link naar de Stelselcatalogus worden toegevoegd.:

https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/ -> https://www.stelselcatalogus.nl/registraties/BAG/
https://vng-realisatie.github.io/Haal-Centraal-BRK-bevragen/ -> https://www.stelselcatalogus.nl/registraties/BRK/
https://vng-realisatie.github.io/Haal-Centraal-BRP-bevragen/ -> https://www.stelselcatalogus.nl/registraties/BRP
https://vng-realisatie.github.io/Haal-Centraal-HR-bevragen/ -> https://www.stelselcatalogus.nl/registraties/HR/
https://vng-realisatie.github.io/Haal-Centraal-WOZ-bevragen/ -> https://www.stelselcatalogus.nl/registraties/WOZ/
https://vng-realisatie.github.io/Haal-Centraal-BGT-bevragen/ -> https://www.stelselcatalogus.nl/registraties/BGT

**Comment by melsk-r** [comment]
Even voor de duidelijkheid zodat ik begrijp wat je bedoelt:

Wil je:

1. onder het top navigatie menu een uitklap-item met de naam 'Bronnen' toevoegen?
2. of wil je in de side navigatie van de GitHub pages van de betreffende API's juist een item toevoegen met de naam 'Bronnen' en daaraan de gerelateerde link naar de stelselcatalogus hangen?

In het eerste geval neem ik aan dat je dezelfde kopjes wil gebruiken als onder 'Producten' (tenminste die kopjes die van toepassing zijn) maar er nu de gerelateerde link naar de stelselcatalogus aan wil hangen.

Moet je in het tweede geval niet spreken over 'Bron'?

**Comment by melsk-r** [comment]
Aangepast in zowel de readme.md als (waar van toepassing) in docs/index.md.

**Comment by fsamwel** [comment]
is nog niet overal doorgevoerd, bijv. BRP historie en bewoning

**Comment by fsamwel** [comment]
het hoeft toch niet bij BRP historie en bewoning
