### ISSUE TITLE
BRP burgerlijke staat toevoegen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#55]
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/528

hier is opnieuw gevraagd wat de status hiervan is. Nu wel oppakken? Of antwoorden dat (en waarom) we het later (of niet) doen?

**Comment by CathyDingemanse** [comment]
Issue aangevuld met vraag naar behoefte: wie en waarvoor het nodig heeft/is. Eerder hadden wij ook al geconstateerd dat e.e.a. breder was dan de huwelijkse staat. Ben benieuwd.
