### ISSUE TITLE
BRK indeling yaml zuiverder maken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#57]
Domain bevat alle inhoud, specifieke yaml (bijv. beslag.yaml) bevat alleen HAL componenten.

Dus inhoudelijke componenten verplaatsen van hypotheek.yaml, beslag.yaml, enz. naar Domain.yaml

**Comment by fsamwel** [comment]
uiteindelijk willen we ook de Domain.yaml opsplitsen. Een fijnmaziger opdeling zorgt dat je makkelijker zonder marge conflicten losse features maken en mergen.

**Comment by fsamwel** [comment]
Johan denk dat dit al gedaan is. Robert checkt dit nog extra

**Comment by JohanBoer** [comment]
Zojuist de develop-branch van BRK-bevraging gechecked. Alle inhoudelijke schema-componenten staan in de Domain.yaml en alle HAL-gerelateerde schemacomponenten en endpoints staan beschreven in een yaml per resource. 

> uiteindelijk willen we ook de Domain.yaml opsplitsen. Een fijnmaziger opdeling zorgt dat je makkelijker zonder merge conflicten losse features maken en mergen.

Hierover wil ik graag nog een keer de discussie aangaan. Ik ben namelijk benieuwd in hoeverre de merge-conflicten te wijten zijn aan het feit dat alle inhoudelijke schema-componentnen in 1 yaml-file zijn opgenomen.
