### ISSUE TITLE
Haal Centraal logo niet gevonden op BRP-RvIG

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#58]
Op https://vng-realisatie.github.io/Haal-Centraal-BRP-Bevragen-RvIG/ wordt het Haal Centraal logo niet gevonden

<img src="/Haal-Centraal-BRP-bevragen-RvIG/assets/img/haal_centraal_zon_geel_RGB.png" width="238px">

**Comment by fsamwel** [comment]
@melsk-r kan jij dit oplossen?

**Comment by melsk-r** [comment]
Ik ga er naar kijken. Het betreft overigens meer dan alleen het Haal Centraal logo. Ook het VNG logo ontbreekt en de link met het css bestand is ook incorrect gezien de opmaak.

**Comment by MelvLee** [comment]
@melsk-r, ik denk dat het komt door casing. In de _config.yaml staat `baseurl: "/Haal-Centraal-BRP-bevragen-RvIG"`. Dit moet `baseurl: "/Haal-Centraal-BRP-Bevragen-RvIG"`zijn. Bevragen met hoofdletter b. Dan komt de naam overeen met de naam van de repo. Voor Linux servers is de url case sensitive

**Comment by melsk-r** [comment]
Probleem is opgelost. Het zat hem in het gebruik van de verkeerde url van de repo in het '_config.yml' bestand. 

'https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen-RvIG'
i.p.v. het correcte
'https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG'

Ik sluit dit issue meteen.

**Comment by melsk-r** [comment]
Ik zie dat we tegelijkertijd de oplossing hebben gevonden... :-)
