### ISSUE TITLE
genereren faalt op BRP RvIG repo

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#59]
na het mergen van pull requests faalt generatie-sdks:

```
 ! [rejected]        master -> master (fetch first)
415
error: failed to push some refs to 'https://github.com/VNG-Realisatie/Haal-Centraal-BRP-Bevragen-RvIG'
416
hint: Updates were rejected because the remote contains work that you do
417
hint: not have locally. This is usually caused by another repository pushing
418
hint: to the same ref. You may want to first integrate the remote changes
419
hint: (e.g., 'git pull ...') before pushing again.
420
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
421
Error: Process completed with exit code 1.
```

**Comment by fsamwel** [comment]
@MelvLee kan jij dit oplossen?

**Comment by MelvLee** [comment]
Het komt doordat 2 actions (generate-sdk's & generate-postman-collection) tegelijk worden getriggered. Als ze klaar zijn doen ze allebei een commit & push, maar een push mag alleen als er geen remote changes zijn. Ik ga de scripts aanpassen.

**Comment by fsamwel** [comment]
ook op BRP-bevragen heb ik een issue met de lint:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/37143495/109622699-b2072900-7b3c-11eb-8f27-d1f55d58dd2c.png">

zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/806

**Comment by MelvLee** [comment]
Nee, het is een andere probleem. Daar heb ik al een fix voor gecommit. Alleen wordt die fix niet gebruikt in de P.R.

**Comment by fsamwel** [comment]
ik heb de pull request nu gemerged, maar krijg dan nog de foutmelding. Ook na handmatig draaien van de oas-lint workflow.

**Comment by fsamwel** [comment]
kan het zijn dat deze fix in master zit en nog niet in develop?

**Comment by MelvLee** [comment]
Ik zag het. Ik zie dat de package-lock.json file is aangepast. Die heb ik lokaal opnieuw gegenereerd en nu werkt het weer.
