### ISSUE TITLE
waarschuwing over Ubuntu versie bij draaien actions

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#60]
elke action geeft een waarschuwing:
> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816

**Comment by MelvLee** [comment]
Klopt, maar dat is geen probleem. De tooling die we gebruiken hebben er geen last van. We krijgen de melding omdat in de actions is aangegeven dat altijd de laatste versie moet worden gebruikt i.p.v. een specifieke versie

**Comment by melsk-r** [comment]
Kunnen we dit issue daarmee sluiten.

**Comment by MelvLee** [comment]
Ja hoor, ik zal het sluiten
