### ISSUE TITLE
BRP update API generate-sdks faalt

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal#76]
Run npm install
npm ERR! code EINTEGRITY
npm ERR! sha512-pqWQ6ozVfNOUDjrLfm4Pt7q4Q12cGw2HUZgry4Q5+Myxu9nmHRkWBpI0J4+MK0AxbdFtdMTwEGVl7Vd+vEiK+A== integrity checksum failed when using sha512: wanted sha512-pqWQ6ozVfNOUDjrLfm4Pt7q4Q12cGw2HUZgry4Q5+Myxu9nmHRkWBpI0J4+MK0AxbdFtdMTwEGVl7Vd+vEiK+A== but got sha512-aqXhGP7//Gui2+UrEtvxZxSquQVXTpZ7KDxfCcKAF3Vysvw0CViVaW9RZ1j1xlIYqaaaipBoqdqeibkc18PNvA==. (231966 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-01T15_13_37_358Z-debug.log

Error: Process completed with exit code 1.

**Comment by fsamwel** [comment]
dit naar aanleiding van een pull request waarin alleen features zijn toegevoegd. Er is dus niks gewijzigd aan de specificaties o.i.d.

**Comment by JohanBoer** [comment]
Hoi Frank, 

Op welke branch gebeurt dit ? Ik zie op de master geen afgebroken actions.

**Comment by fsamwel** [comment]
oh ik zie het al, ik heb hierop nog een fork en de fout is ook op mijn fork ontstaan
