### ISSUE TITLE
Geldigheidsduur rijbewijs

### ISSUE THREAD

**Issue by ReneZijlstra** [VNG-Realisatie/Haal-Centraal#86]
Als informatiemanager Dienstverlening wil ik de geldigheidsduur van een rijbewijs kunnen tonen in de persoonlijke internetpagina van een inwoner. Deze persoonlijke internetpagina bevind zicht achter een DigiD-inlog. 

 Wordt deze informatie opgenomen in het Federatief Datastelsel en beschikbaar gesteld via HaalCentraal?

**Comment by CathyDingemanse** [comment]
@ReneZijlstra, RvIG organiseert van alles rondom reisdocumenten, maar geen rijbewijzen. Daarvoor moet je bij de RDW zijn.
